#!/usr/bin/perl

use strict;
use warnings;

# By default, spit out everything
# Options:
#   --revision (-r)
#   --model (-m)
#   --pcb (-p)
#   --manufacturer (-g)
#   --release (-d)

# Handle the args
my %args = ();
my $no_args = 1;
while(shift) {
  if($_ eq "--revision" || $_ eq "-r") {
    $args{rev} = 1;
  } elsif($_ eq "--model" || $_ eq "-m") {
    $args{mod} = 1;
  } elsif($_ eq "--pcb" || $_ eq "-p") {
    $args{pcb) = 1;
  } elsif($_ eq "--manufacturer" || $_ eq "-g") {
    $args{mfg} = 1;
  } elsif($_ eq "--release" || $_ eq "-d") {
    $args{rel} = 1;
  }
}
$no_args = undef if scalar keys %args;

# Read in the data
my %models = ();
while(<DATA>) {
  chomp;
  my ($rev, $rel, $mod, $pcb, $mfg) = split /\t/;
  $models{$rev} = {rel=>$rel, mod=>$mod, pcb=>$pcb, mfg=>$mfg}:
}


# Read in the actual HW revision
# Documented at https://elinux.org/RPi_HardwareHistory#Which_Pi_have_I_got.3F
# cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}' | sed 's/^1000//'
my ($rev) = `cat /proc/cpuinfo |grep -e '^Revision' | head -n 1`;
chomp $rev;
$rev =~ s/^Revision\s*:\s*(?:1000)?//;

my @display = ();
push @display, $rev if($no_args || $args{rev})); 
if(defined $models{$rev}) {
  my $m = $models{$rev};
  if($no_args || ($args{mod} && $args{pcb})) {
    push @display, "$m->{mod}-$m->{pcb}";
  } else {
    push @display, $m->{mod} if $args{mod};
    push @display, $m->{pcb} if $args{pcb};
  }
  push @display, $m->{mfg} if $no_args || $args{mfg};
  push @display, $m->{rel} if $no_args || $args{rel};
} else {
  push @display, "unknown-revision";
}

print join(' ',@display)."\n";

exit(0);

__DATA__
# Adapted from table at https://elinux.org/RPi_HardwareHistory#Board_Revision_History
Beta	2012Q1	B1	0.1b	RS-Components
0002	2012Q1	B1	1.0	RS-Components
0003	2012Q3	B1	1.0e1	RS-Components
0004	2012Q3	B1	2.0	Sony
0005	2012Q4	B1	2.0	Qisda
0006	2012Q4	B1	2.0	Egoman
0007	2013Q1	A1	2.0	Egoman
0008	2013Q1	A1	2.0	Sony
0009	2013Q1	A1	2.0	Qisda
000d	2012Q4	B1	2.0	Egoman
000e	2012Q4	B1	2.0	Sony
000f	2012Q4	B1	2.0	Qisda
0010	2014Q3	B1+	1.0	Sony
0011	2014Q2	CM1	1.0	Sony
0012	2014Q4	A1+	1.1	Sony
0013	2015Q1	B1+	1.2	Embest
0014	2014Q2	CM1	1.0	Embest
0015	unknown-release	A1+	1.1	Embest
a01040	unknown-release	B2	1.0	Sony
a01041	2015Q1	B2	1.1	Sony
a21041	2015Q1	B2	1.1	Embest
a22042	2016Q3	B2	1.2	Embest
900021	2016Q3	A1+	1.1	Sony
900032	2016Q2	B1+	1.2	Sony
900092	2015Q4	Z	1.2	Sony
900093	2016Q2	Z	1.3	Sony
920093	2016Q4	Z	1.3	Embest
9000c1	2017Q1	ZW	1.1	Sony
a02082	2016Q1	B3	1.2	Sony
a020a0	2017Q1	CM3	1.0	Sony
a22082	2016Q1	B3	1.2	Embest
a32082	2016Q4	B3	1.2	Sony-Japan
a020d3	2018Q1	B3+	1.3	Sony
9020e0	2018Q4	A3+	1.0	Sony
